"""
Version and identity information for the application.
Format: {app_name}/{version}@{git_hash}
Example: habitlab/1.0.0@8f1325a

NOTE: This file will be overwritten by GitHub Actions during release.
DO NOT EDIT THIS FILE MANUALLY.
"""

IDENTITY = "habitlab/0.0.0@888888"  # Will be set to git commit hash (e.g. "habitlab/1.0.0@8f1325a")
VERSION = "v0.0.0"
